version: 2

project_name: serversentry

before:
  hooks:
    - go mod tidy

builds:
  - id: serversentry
    binary: serversentry
    main: cmd/hub/hub.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm

  - id: serversentry-agent
    binary: serversentry-agent
    main: cmd/agent/agent.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - mips64
      - riscv64
      - mipsle
      - ppc64le
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: riscv64

archives:
  - id: serversentry-agent
    formats: [tar.gz]
    builds:
      - serversentry-agent
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: serversentry
    formats: [tar.gz]
    builds:
      - serversentry
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}

nfpms:
  - id: serversentry-agent
    package_name: serversentry-agent
    description: |-
      Agent for ServerSentry
      ServerSentry is a lightweight server monitoring platform that includes Docker
      statistics, historical data, and alert functions. It has a friendly web
      interface, simple configuration, and is ready to use out of the box.
      It supports automatic backup, multi-user, OAuth authentication, and
      API access.
    maintainer: nak-ventures <oss@nak-ventures.com>
    section: net
    builds:
      - serversentry-agent
    formats:
      - deb
    contents:
      - src: ../supplemental/debian/serversentry-agent.service
        dst: lib/systemd/system/serversentry-agent.service
        packager: deb
      - src: ../supplemental/debian/copyright
        dst: usr/share/doc/serversentry-agent/copyright
        packager: deb
      - src: ../supplemental/debian/lintian-overrides
        dst: usr/share/lintian/overrides/serversentry-agent
        packager: deb
    scripts:
      postinstall: ../supplemental/debian/postinstall.sh
      preremove: ../supplemental/debian/prerm.sh
      postremove: ../supplemental/debian/postrm.sh
    deb:
      predepends:
        - adduser
        - debconf
      scripts:
        templates: ../supplemental/debian/templates
        # Currently broken due to a bug in goreleaser
        # https://github.com/goreleaser/goreleaser/issues/5487
        #config: ../supplemental/debian/config.sh

scoops:
  - ids: [serversentry-agent]
    name: serversentry-agent
    repository:
      owner: nak-ventures
      name: serversentry-scoops
    homepage: "https://serversentry.dev"
    description: "Agent for ServerSentry, a lightweight server monitoring platform."
    license: MIT

# # Needs choco installed, so doesn't build on linux / default gh workflow :(
# chocolateys:
#   - title: ServerSentry Agent
#     ids: [serversentry-agent]
#     package_source_url: https://github.com/nak-ventures/serversentry-chocolatey
#     owners: nak-ventures
#     authors: nak-ventures
#     summary: 'Agent for ServerSentry, a lightweight server monitoring platform.'
#     description: |
#       ServerSentry is a lightweight server monitoring platform that includes Docker statistics, historical data, and alert functions.

#       It has a friendly web interface, simple configuration, and is ready to use out of the box. It supports automatic backup, multi-user, OAuth authentication, and API access.
#     license_url: https://github.com/nak-ventures/serversentry/blob/main/LICENSE
#     project_url: https://serversentry.dev
#     project_source_url: https://github.com/nak-ventures/serversentry
#     docs_url: https://serversentry.dev/guide/getting-started
#     icon_url: https://cdn.jsdelivr.net/gh/nak-ventures/serversentry-icons/png/serversentry.png
#     bug_tracker_url: https://github.com/nak-ventures/serversentry/issues
#     copyright: 2025 nak-ventures
#     tags: foss cross-platform admin monitoring
#     require_license_acceptance: false
#     release_notes: 'https://github.com/nak-ventures/serversentry/releases/tag/v{{ .Version }}'

brews:
  - ids: [serversentry-agent]
    name: serversentry-agent
    repository:
      owner: nak-ventures
      name: homebrew-serversentry
    homepage: "https://serversentry.dev"
    description: "Agent for ServerSentry, a lightweight server monitoring platform."
    license: MIT
    skip_upload: auto
    extra_install: |
      (bin/"serversentry-agent-launcher").write <<~EOS
        #!/bin/bash
        set -a
        if [ -f "$HOME/.config/serversentry/serversentry-agent.env" ]; then
          source "$HOME/.config/serversentry/serversentry-agent.env"
        fi
        set +a
        exec #{bin}/serversentry-agent "$@"
      EOS
      (bin/"serversentry-agent-launcher").chmod 0755
    service: |
      run ["#{bin}/serversentry-agent-launcher"]
      log_path "#{Dir.home}/.cache/serversentry/serversentry-agent.log"
      error_log_path "#{Dir.home}/.cache/serversentry/serversentry-agent.log"
      keep_alive true
      restart_delay 5
      process_type :background

winget:
  - ids: [serversentry-agent]
    name: serversentry-agent
    package_identifier: nak-ventures.serversentry-agent
    publisher: nak-ventures
    license: MIT
    license_url: "https://github.com/nak-ventures/serversentry/blob/main/LICENSE"
    copyright: "2025 nak-ventures"
    homepage: "https://serversentry.dev"
    release_notes_url: "https://github.com/nak-ventures/serversentry/releases/tag/v{{ .Version }}"
    publisher_support_url: "https://github.com/nak-ventures/serversentry/issues"
    short_description: "Agent for ServerSentry, a lightweight server monitoring platform."
    skip_upload: auto
    description: |
      ServerSentry is a lightweight server monitoring platform that includes Docker
      statistics, historical data, and alert functions. It has a friendly web
      interface, simple configuration, and is ready to use out of the box.
      It supports automatic backup, multi-user, OAuth authentication, and
      API access.
    tags:
      - homelab
      - monitoring
      - self-hosted
    repository:
      owner: nak-ventures
      name: serversentry-winget
      branch: nak-ventures.serversentry-agent-{{ .Version }}
      token: "{{ .Env.WINGET_TOKEN }}"
      # pull_request:
      #   enabled: true
      #   draft: false
      #   base:
      #     owner: microsoft
      #     name: winget-pkgs
      #     branch: master

release:
  draft: true

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
