name: Make release and binaries

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --no-save --cwd ./serversentry/site

      - name: Build site
        run: bun run --cwd ./serversentry/site build

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22.1"

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Build .NET LHM executable for Windows sensors
        run: |
          dotnet build -c Release ./serversentry/internal/agent/lhm/serversentry_lhm.csproj
        shell: bash

      - name: GoReleaser serversentry
        uses: goreleaser/goreleaser-action@v6
        with:
          workdir: ./serversentry
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN || secrets.GITHUB_TOKEN }}
          WINGET_TOKEN: ${{ secrets.WINGET_TOKEN }}
